### ISSUE TITLE
Issues with launches causing NPE and WebRender fails no falling back on H3?

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-heritrix#52]
Couple of issues.

Firstly, observing some:

```
java.lang.NullPointerException
        at uk.bl.wap.crawler.prefetch.QuotaResetPropagationProcessor.shouldProcess(QuotaResetPropagationProcessor.java:22)
        at org.archive.modules.Processor.process(Processor.java:140)
        at org.archive.modules.ProcessorChain.process(ProcessorChain.java:131)
        at org.archive.crawler.postprocessor.CandidatesProcessor.runCandidateChain(CandidatesProcessor.java:176)
        at uk.bl.wap.crawler.frontier.KafkaUrlReceiver$CrawlMessageFrontierScheduler.run(KafkaUrlReceiver.java:545)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

So presumably there's some basic bug there.

Also, seeing some 'skipped' days for the odd seed. Correlated with failed WebRender events. Implies failed WebRender events are not falling back on H3 correctly.

Finally, it appears we have so many Twitter seeds, we're not getting through them all in a day!  Need to use a sheet with parallel queues setup.

**Comment by anjackson** [comment]
Some fixes in place, but can't test yet due to networking problems.

**Comment by anjackson** [comment]
okay, built and home and the changes so far seem solid enough!

**Comment by anjackson** [comment]
Note also changes in `webrender-api` were made to make it try harder/wait longer when contacting Docker to run screenshotters.  That was the root cause of many of the gaps, as the DNS + robots.txt + 3 x WebRender meant the crawl ran our of retries (only 5 were allowed, now upped to 10).

**Comment by anjackson** [comment]
Okay, looking solid. Tomorrow, I'll analyse today's crawl activity and check things have improved, but it's looking good.

**Comment by anjackson** [comment]
Definite improvement, but some other issues around launching came up (not all seeds marked as seeds, launch failures not caught). Twitter overload remains an issue, and we'll still need parallel queues at some point.

**Comment by anjackson** [comment]
Now seen that lodging `connect_failed` in OutbackCDX means that if the WebRender fails entirely, the URL is never recrawled because it's considered 'recently seen'. Modifying the OutbackCDX Persist Store hook to ignore HTTP transient errors.
